spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smartstock3?serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Amit1@sumit
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: amitksinghmdv@gmail.com
    password: kxvxhrvzpqzhudao
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

server:
 port: 8090
 servlet:
  encoding:
   charset: UTF-8
   force: true

app:
  email:
    from: amitksinghmdv@gmail.com